"""
synthesis/assembler.py — Assemble(L, SF) → PF serialisable program.

Takes a generated fill() code string and wraps it into a complete,
importable Python module with proper header, imports, and metadata.
"""
from __future__ import annotations
import hashlib
from datetime import datetime

PROGRAM_TEMPLATE = '''\
# PF: {form_id}
# Auto-generated by HPE-AFF GF(F, theta_F, L)
# Generated: {generated_at}
# Score:     {score}
# Candidate: {candidate_id}
# DO NOT EDIT BY HAND — re-run synthesis to update

from primitives.transforms import (
    apply_date_transform,
    apply_number_transform,
    apply_currency_transform,
)

{fill_code}
'''


def assemble_program(
    form_id: str,
    fill_code: str,
    score: float | None = None,
    candidate_id: str | None = None,
) -> str:
    """Wrap a raw fill() code snippet into a complete PF module.

    Args:
        form_id:      Form family identifier.
        fill_code:    Python code string containing the fill() function.
        score:        Validation score achieved (for header metadata).
        candidate_id: Candidate ID from the evolution pool.

    Returns:
        Complete Python source string ready to write to a .py file.
    """
    return PROGRAM_TEMPLATE.format(
        form_id=form_id,
        generated_at=datetime.utcnow().isoformat() + "Z",
        score=score if score is not None else "pending",
        candidate_id=candidate_id or "n/a",
        fill_code=fill_code,
    )


def program_hash(fill_code: str) -> str:
    """Compute a stable SHA-256 hash for a fill() code string.
    Used as cache key suffix to detect template changes.
    """
    return hashlib.sha256(fill_code.encode()).hexdigest()[:16]
